package com.pie.whatsappstatussaver.localization

import com.pie.whatsappstatussaver.R

object MyConstant {
    val COUNTRY_LIST = listOf(
        LangCountryModel(0, "English", "en", R.drawable.english),
        LangCountryModel(1, "Afrikaans", "af", R.drawable.afrikaans),
        LangCountryModel(2, "Albanian", "sq", R.drawable.albanian),
        LangCountryModel(3, "Amharic", "am", R.drawable.amharic),
        LangCountryModel(4, "Arabic", "ar", R.drawable.arabic),
        LangCountryModel(5, "Armenian", "hy", R.drawable.armenian),
        LangCountryModel(6, "Azerbaijani", "az", R.drawable.azerbaijani),
        LangCountryModel(7, "Basque", "eu", R.drawable.basque),
        LangCountryModel(8, "Belarusian", "be", R.drawable.belarusian),
        LangCountryModel(9, "Bengali", "bn", R.drawable.bengali),
        LangCountryModel(10, "Bosnian", "bs", R.drawable.bosnian),
        LangCountryModel(11, "Bulgarian", "bg", R.drawable.bulgarian),
        LangCountryModel(12, "Catalan", "ca", R.drawable.catalan),
        LangCountryModel(13, "Cebuano", "ceb", R.drawable.cebuano),
        LangCountryModel(14, "Chichewa", "ny", R.drawable.chichewa),
        LangCountryModel(15, "Chinese Simplified", "zh", R.drawable.chinese_simplified),
        LangCountryModel(16, "Chinese Traditional", "zh", R.drawable.chinese_traditional),
        LangCountryModel(17, "Corsican", "co", R.drawable.corsican),
        LangCountryModel(18, "Croatian", "hr", R.drawable.croatian),
        LangCountryModel(19, "Czech", "cs", R.drawable.czech),
        LangCountryModel(20, "Danish", "da", R.drawable.danish),
        LangCountryModel(21, "Dutch", "nl", R.drawable.dutch),
        LangCountryModel(22, "Esperanto", "eo", R.drawable.esperanto),
        LangCountryModel(23, "Estonian", "et", R.drawable.estonian),
        LangCountryModel(24, "Filipino", "tl", R.drawable.filipino),
        LangCountryModel(25, "Finnish", "fi", R.drawable.finnish),
        LangCountryModel(26, "French", "fr", R.drawable.french),
        LangCountryModel(27, "Frisian", "fy", R.drawable.frisian),
        LangCountryModel(28, "Galician", "gl", R.drawable.galician),
        LangCountryModel(29, "Georgian", "ka", R.drawable.georgian),
        LangCountryModel(30, "German", "de", R.drawable.german),
        LangCountryModel(31, "Greek", "el", R.drawable.greek),
        LangCountryModel(32, "Gujarati", "gu", R.drawable.gujarati),
        LangCountryModel(33, "Haitian Creole", "ht", R.drawable.haitian_creole),
        LangCountryModel(34, "Hausa", "ha", R.drawable.hausa),
        LangCountryModel(35, "Hawaiian", "haw", R.drawable.hawaiian),
        LangCountryModel(36, "Hebrew", "iw", R.drawable.hebrew),
        LangCountryModel(37, "Hindi", "hi", R.drawable.hindi),
        LangCountryModel(38, "Hmong", "hmn", R.drawable.hmong),
        LangCountryModel(39, "Hungarian", "hu", R.drawable.hungarian),
        LangCountryModel(40, "Icelandic", "is", R.drawable.islandic),
        LangCountryModel(41, "Igbo", "ig", R.drawable.igbo),
        LangCountryModel(42, "Indonesian", "in", R.drawable.indonesian),
        LangCountryModel(43, "Irish", "ga", R.drawable.irish),
        LangCountryModel(44, "Italian", "it", R.drawable.italian),
        LangCountryModel(45, "Japanese", "ja", R.drawable.japanese),
        LangCountryModel(46, "Javanese", "jw", R.drawable.javanese),
        LangCountryModel(47, "Kannada", "kn", R.drawable.kannada),
        LangCountryModel(48, "Kazakh", "kk", R.drawable.kazakh),
        LangCountryModel(49, "Khmer", "km", R.drawable.khmer),
        LangCountryModel(50, "Korean", "ko", R.drawable.korean),
        LangCountryModel(51, "Kurdish", "ku", R.drawable.kurdish),
        LangCountryModel(52, "Kyrgyz", "ky", R.drawable.kyrgyz),
        LangCountryModel(53, "Lao", "lo", R.drawable.lao),
        LangCountryModel(54, "Latin", "la", R.drawable.latin),
        LangCountryModel(55, "Latvian", "lv", R.drawable.latvian),
        LangCountryModel(56, "Lithuanian", "lt", R.drawable.lithuanian),
        LangCountryModel(57, "Luxembourgish", "lb", R.drawable.luxembourgish),
        LangCountryModel(58, "Macedonian", "mk", R.drawable.macedonian),
        LangCountryModel(59, "Malagasy", "mg", R.drawable.malagasy),
        LangCountryModel(60, "Malay", "ms", R.drawable.malay),
        LangCountryModel(61, "Malayalam", "ml", R.drawable.malayalam),
        LangCountryModel(62, "Maltese", "mt", R.drawable.maltese),
        LangCountryModel(63, "Maori", "mi", R.drawable.maori),
        LangCountryModel(64, "Marathi", "mr", R.drawable.marathi),
        LangCountryModel(65, "Mongolian", "mn", R.drawable.mongolian),
        LangCountryModel(66, "Myanmar", "my", R.drawable.myanmar),
        LangCountryModel(67, "Nepali", "ne", R.drawable.nepali),
        LangCountryModel(68, "Norwegian", "no", R.drawable.norwegian),
        LangCountryModel(69, "Pashto", "ps", R.drawable.pashto),
        LangCountryModel(70, "Persian", "fa", R.drawable.persian),
        LangCountryModel(71, "Polish", "pl", R.drawable.polish),
        LangCountryModel(72, "Portuguese", "pt", R.drawable.portuguese),
        LangCountryModel(73, "Punjabi", "pa", R.drawable.punjabi),
        LangCountryModel(74, "Romanian", "ro", R.drawable.romanian),
        LangCountryModel(75, "Russian", "ru", R.drawable.russian),
        LangCountryModel(76, "Samoan", "sm", R.drawable.samoan),
        LangCountryModel(77, "Scots Gaelic", "gd", R.drawable.scots_gaelic),
        LangCountryModel(78, "Serbian", "sr", R.drawable.serbian),
        LangCountryModel(79, "Sesotho", "st", R.drawable.sesotho),
        LangCountryModel(80, "Shona", "sn", R.drawable.shona),
        LangCountryModel(81, "Sindhi", "sd", R.drawable.sindhi),
        LangCountryModel(82, "Sinhala", "si", R.drawable.sinhala),
        LangCountryModel(83, "Slovak", "sk", R.drawable.slovak),
        LangCountryModel(84, "Slovenian", "sl", R.drawable.slovanian),
        LangCountryModel(85, "Somali", "so", R.drawable.somali),
        LangCountryModel(86, "Spanish", "es", R.drawable.spanish),
        LangCountryModel(87, "Sundanese", "su", R.drawable.sundanese),
        LangCountryModel(88, "Swahili", "sw", R.drawable.swahili),
        LangCountryModel(89, "Swedish", "sv", R.drawable.swedish),
        LangCountryModel(90, "Tajik", "tg", R.drawable.tajik),
        LangCountryModel(91, "Tamil", "ta", R.drawable.tamil),
        LangCountryModel(92, "Telugu", "te", R.drawable.telugu),
        LangCountryModel(93, "Thai", "th", R.drawable.thai),
        LangCountryModel(94, "Turkish", "tr", R.drawable.turkish),
        LangCountryModel(95, "Ukrainian", "uk", R.drawable.ukrainian),
        LangCountryModel(96, "Urdu", "ur", R.drawable.urdu),
        LangCountryModel(97, "Uzbek", "uz", R.drawable.uzbek),
        LangCountryModel(98, "Vietnamese", "vi", R.drawable.vietnamese),
        LangCountryModel(99, "Welsh", "cy", R.drawable.welsh),
        LangCountryModel(100, "Xhosa", "xh", R.drawable.xhosa),
        LangCountryModel(101, "Yoruba", "yo", R.drawable.yoruba),
        LangCountryModel(102, "Zulu", "zu", R.drawable.zulu)
    )
}